flowchart >
    input["Input (Config)"]
    setup[State]

    runtime[Runtime]

    lifecycle["Lifecycle"]


    lifecycle0["Setup"]
    lifecycle1["load state"]
    lifecycle2["Transformer"]
    lifecycle3["Output"]

    version[Bump]
    manifest[Manifest]

    input --> setup --> runtime --> lifecycle --> lifecycle0
    lifecycle --> lifecycle1
    lifecycle --> lifecycle2
    lifecycle --> lifecycle3
    runtime --> version
    runtime --> manifest
