flowchart TD
    user["User (Signer)"]
    node0["Client node (Committer)"]
    node1["Storage node (Committee)"]
    host["Client host (router)"]
    blockchain["Blockchain"]

    user --> host --> node0
             host --> node1
             host --> blockchain
             blockchain --> node1