mindmap
  root((mindmap))
    Learning center
    Auditor Registry Rollup
      Auditor gives trust to earn incencitives per deployed proof
      Auditor stake their tokens to become trustful in the community
    
    Developer Registry Rollup
      Developers can only request trust per stateless plugin
      Developer is free to develop plugins
      Developer can stake tokens to earn incencitives for each time list developer deploys a proof

    Plugins Store Rollup
      Developer publishes program
      Developer earns incencitives on each proof deployed on L2
      Auditors gives trust for given program  

    Compiled List Rollup
      Workflow config file
        integrations
          Github bot
          Discord bot
          Telegram bot
          Wallet integration
          Dapp integration
